name: cakemain
description: "Um aplicativo de venda de bolos."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.0 # DIRECIONA AOS LINKS DE NAVEGADOR/APPS
  hive: ^2.2.3 # BANCO DE DADOS CASUAL (ITENS, PEDIDOS, CONTAS E ALTERAÇÕES DO APP)
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2 # OPÇÃO SIMPLES DE BANCO DE DADOS (LOGIN DE TESTE, ALTERAÇÃO DE IDIOMA, PEPITO)
  image_picker: ^1.1.2 # IMAGENS
  path_provider: ^2.1.1 # SALVAR IMAGENS LOCALMENTE
  flutter_local_notifications: ^18.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1 # ÍCONES (ANDROID)

flutter:
  uses-material-design: true

  assets:
    - assets/images/

# CONFIGURAÇÃO DO ÍCONE
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_foreground_inset: 0